### PR TITLE
Add bin

### PR DESCRIPTION
**Pull request by dalance**
This PR adds a binary to dump target information.
I think this is useful to investigate user environment which is broken at `#cfg[]`.

### CODE REVIEW

**Comment by casey** [comment]
This sounds like a good idea.

Why don't we put it in `src/main.rs`, and then we don't need to have the entry in `Cargo.toml`. Also, you'll be able to do `cargo install target`, and the binary will just be called `target`, which I like.

For the output, what do you think about removing `target_` in the print statements? So it's just, e.g. `println!("arch: {}", target::arch());`

**Comment by casey** [comment]
Also, this could use a integration test that builds and runs the binary and checks that the output is correct.

In `tests/binary.rs` should be something like:

```rust
use executable_path::executable_path;

#[test]
fn binary_output() {
  assert_eq!(
    str::from_utf8(&Command::new(executable_path("target")).output().unwrap().stdout).unwrap(),
    "EXPECTED OUTPUT",
  );
}
```

(`executable_path` is a crate that will give you the path to the built binary.)

**Comment by dalance** [comment]
Thank you for your suggestion.
I'll refine after #3 merged.

**Comment by casey** [comment]
Awesome, looks great!

**Comment by casey** [comment]
I just bumped the version to 1.1.0 and published it to crates.io.

**Pull request merged**
