### PR TITLE
Add GNU/Hurd support

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by casey** [comment]
Thank you for the PR!

**Comment by casey** [comment]
By the way, let me know if you need this in a release. `target` has few users, so I basically only cut a release when someone needs one.

**Comment by sthibaul** [comment]
I thought I needed it for some debian package, but only a couple actually, so it's not really worth

**Comment by casey** [comment]
I just released 2.1.0, which contains this PR. Doing my part to make GNU/Hurd happen 🫡

**Pull request merged**
